import difference from "lodash/difference";
import pick from "lodash/pick";
import flatMap from "lodash/flatMap";

import { AppState } from "@/store";

import {
  connectionsByIdSelector,
  nodeInputConnectionIdsFromNodeIdSelector,
  nodeOutputConnectionIdsFromNodeIdSelector,
} from "@/services/node-graph/selectors/connections";

import { NodeLayoutServiceState } from "../../state";
import { nodePinsFromPinNodeSelector } from "@/services/node-graph/selectors/pins";
import { nodePinEquals } from "@/services/node-graph/types";

export default function nodeDelete(
  state: NodeLayoutServiceState,
  nodeIds: string[],
  rootState: AppState
): NodeLayoutServiceState {
  // Connection ids connected to nodes being removed.
  const removingNodeConnectionIds = nodeIds.reduce((connectionIds, nodeId) => {
    // Get all inputs and outputs to the node.
    const inputs = nodeInputConnectionIdsFromNodeIdSelector(rootState, nodeId);
    const outputs = nodeOutputConnectionIdsFromNodeIdSelector(
      rootState,
      nodeId
    );

    connectionIds.push(...inputs, ...outputs);

    return connectionIds;
  }, [] as string[]);

  // Connections going to IC node pins whose pin nodes were removed.
  const removedIcPins = flatMap(nodeIds, (nodeId) =>
    // If not a pin, this will return an empty array.
    nodePinsFromPinNodeSelector(rootState, nodeId)
  );
  const connectionsById = connectionsByIdSelector(rootState);
  const removingPinConnectionIds = Object.keys(connectionsById).filter(
    (connectionId) => {
      const { inputPin, outputPin } = connectionsById[connectionId];
      // We will need to remove this connection if it went to a pin generated by
      // an input or output pin node being removed.
      return removedIcPins.some(
        (removedPin) =>
          nodePinEquals(removedPin, inputPin) ||
          nodePinEquals(removedPin, outputPin)
      );
    }
  );

  const removingConnectionIds = [
    ...removingNodeConnectionIds,
    ...removingPinConnectionIds,
  ];

  // Remove any joint that is part of a removed connection.
  const removingJointIds = removingConnectionIds.reduce(
    (jointIds, connectionId) => {
      jointIds.push(...state.wireJointIdsByConnectionId[connectionId]);
      return jointIds;
    },
    [] as string[]
  );

  const remainingConnectionIds = difference(
    Object.keys(state.wireJointIdsByConnectionId),
    removingNodeConnectionIds
  );

  const remainingJointIds = difference(
    Object.keys(state.wireJointPositionsByJointId),
    removingJointIds
  );

  const remainingNodeIds = difference(
    Object.keys(state.nodePositionsById),
    nodeIds
  );

  return {
    ...state,
    nodePositionsById: pick(state.nodePositionsById, remainingNodeIds),
    wireJointIdsByConnectionId: pick(
      state.wireJointIdsByConnectionId,
      remainingConnectionIds
    ),
    wireJointPositionsByJointId: pick(
      state.wireJointPositionsByJointId,
      remainingJointIds
    ),
  };
}
